### ISSUE TITLE
CaniAssets > All Asset > user not able to sort by IMEI until select S NO in Cloums 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/caniset#15]
**What's not working **
CaniAssets > All Asset > user not able to sort by IMEI.
![Screenshot 2023-06-05 134204](https://github.com/canaris-in/caniset/assets/114991909/11411d87-fc27-42e1-bdec-f63c0fac1796)

**Comment by rajeshcanaris** [comment]
its empty that why its not working but when you have more than to or three imfi the its work its not an error
![Screenshot from 2023-07-26 21-36-50](https://github.com/canaris-in/caniset/assets/133959091/85cfb9c9-b0b3-4469-a5c1-96231d81a88f)
![Screenshot from 2023-07-26 21-53-08](https://github.com/canaris-in/caniset/assets/133959091/eea0b15e-7a68-48de-bba4-ac4fc7997125)

**Comment by lalit510** [comment]
it's working now
