### ISSUE TITLE
server error display when user accept asset. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/caniset#16]
**What's not working **
after checkout Asset then other user accept the Asset show server error 
![Screenshot 2023-06-05 152031](https://github.com/canaris-in/caniset/assets/114991909/27a00f63-9097-4b0b-bc93-5e14525e3fdd)
 

**Expected **
Server Error should not be display.

**Comment by lalit510** [comment]
server error again displays please fix the error.

**Comment by rajeshcanaris** [comment]
Sir Now PR is merge you can check now.

**Comment by lalit510** [comment]
again, show the error.

**Comment by lalit510** [comment]
it's working now
