### ISSUE TITLE
CaniAssets > Licenses > user not able to Checkin License Seat 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/caniset#21]
**What's not working **
CaniAssets > Licenses > user not able to Checkin License Seat 
![Screenshot 2023-06-06 172933](https://github.com/canaris-in/caniset/assets/114991909/65698fa1-6657-4310-af6a-8221102200fc)

**Expected **
Checkin License seat should be working properly

**Comment by rajeshcanaris** [comment]
![Screenshot from 2023-07-24 16-31-00](https://github.com/canaris-in/caniset/assets/133959091/d4122391-544d-4998-9008-99bfaa5bb109)
here if you click on Reassignable checkbox after you can assign anyone.
![Screenshot from 2023-07-24 16-33-18](https://github.com/canaris-in/caniset/assets/133959091/229c03ad-2f4a-440f-814d-b295b0759d9f)

**Comment by lalit510** [comment]
it's working now
